### PR TITLE
Add second example

### PR DESCRIPTION
**Pull request by SteveBarnett**

### CODE REVIEW

**Comment by SteveBarnett** [comment]
@avermeulen For your checkings, please.

**Comment by SteveBarnett** [comment]
@avermeulen Happy with this?

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Comment by avermeulen** [comment]
@SteveBarnett the traffic light dash examples are not consistent. They will need a different approach each I think.

**Comment by SteveBarnett** [comment]
@avermeulen Rejiggled. How's this?

**Comment by SteveBarnett** [comment]
@avermeulen Ping!

**Pull request merged**
